// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// system / user / assistant / tool
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    /// optional, for tool role
    #[prost(string, tag = "3")]
    pub tool_call_id: ::prost::alloc::string::String,
    /// optional, for assistant role with tool calls
    #[prost(message, repeated, tag = "4")]
    pub tool_calls: ::prost::alloc::vec::Vec<ToolCall>,
    /// optional, for multimodal (vision/file) content
    #[prost(message, repeated, tag = "5")]
    pub parts: ::prost::alloc::vec::Vec<MultiModalPart>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MultiModalPart {
    /// e.g. image/png, image/jpeg
    #[prost(string, tag = "1")]
    pub content_type: ::prost::alloc::string::String,
    /// base64-encoded bytes
    #[prost(string, tag = "2")]
    pub data: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolCall {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// JSON object
    #[prost(string, tag = "3")]
    pub arguments: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    /// e.g. openai, anthropic
    #[prost(string, tag = "3")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub tool_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "6")]
    pub stream: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatResponse {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub message: ::core::option::Option<Message>,
    #[prost(message, repeated, tag = "3")]
    pub tool_calls: ::prost::alloc::vec::Vec<ToolCall>,
    #[prost(message, optional, tag = "4")]
    pub usage: ::core::option::Option<Usage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatStreamChunk {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub delta: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub done: bool,
    /// final message when done
    #[prost(message, optional, tag = "4")]
    pub message: ::core::option::Option<Message>,
    #[prost(message, repeated, tag = "5")]
    pub tool_calls: ::prost::alloc::vec::Vec<ToolCall>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Usage {
    #[prost(uint32, tag = "1")]
    pub prompt_tokens: u32,
    #[prost(uint32, tag = "2")]
    pub completion_tokens: u32,
    #[prost(uint32, tag = "3")]
    pub total_tokens: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListModelsRequest {
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsResponse {
    #[prost(message, repeated, tag = "1")]
    pub models: ::prost::alloc::vec::Vec<ModelInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteToolRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// JSON object
    #[prost(string, tag = "2")]
    pub arguments: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteToolResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub output: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// JSON schema
    #[prost(string, tag = "3")]
    pub parameters_schema: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListToolsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListToolsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tools: ::prost::alloc::vec::Vec<ToolInfo>,
}
include!("rsmgo.v1.tonic.rs");
// @@protoc_insertion_point(module)
